tracks = [
    {
        "name":"Futsal Shuffle 2020",
        "id":"song1",
        "album":"album1",
        "artist":"artist1",
        "url":"../static/music/song1.mp3",
        "cover":"../static/image/TrackCover/song1.jpg",
        "genre":"pop",
    },
    {
        "name":"Sauce It Up",
        "id":"song2",
        "album":"album2",
        "artist":"artist1",
        "url":"../static/music/song2.mp3",
        "cover":"../static/image/TrackCover/song2.jpg",
        "genre":"pop",
    },
    {
        "name":"For Real",
        "id":"song3",
        "album":"album2",
        "artist":"artist1",
        "url":"../static/music/song3.mp3",
        "cover":"../static/image/TrackCover/song3.jpg",
        "genre":"pop",
    },
    {
        "name":"Dark Queen",
        "id":"song4",
        "album":"album2",
        "artist":"artist1",
        "url":"../static/music/song4.mp3",
        "cover":"../static/image/TrackCover/song4.jpg",
        "genre":"pop",
    },
    {
        "name":"Safe House",
        "id":"song5",
        "album":"album3",
        "artist":"artist1",
        "url":"../static/music/song5.mp3",
        "cover":"../static/image/TrackCover/song5.jpg",
        "genre":"rock",
    },
    {
        "name":"Right Now",
        "id":"song6",
        "album":"album3",
        "artist":"artist1",
        "url":"../static/music/song6.mp3",
        "cover":"../static/image/TrackCover/song6.jpg",
        "genre":"rock",
    },
    {
        "name":"GTFO",
        "id":"song7",
        "album":"album4",
        "artist":"artist2",
        "url":"../static/music/song7.mp3",
        "cover":"../static/image/TrackCover/song7.jpg",
        "genre":"rock",
    },
    {
        "name":"With You",
        "id":"song8",
        "album":"album4",
        "artist":"artist2",
        "url":"../static/music/song8.mp3",
        "cover":"../static/image/TrackCover/song8.jpg",
        "genre":"rock",
    },
    {
        "name":"Caution",
        "id":"song9",
        "album":"album4",
        "artist":"artist2",
        "url":"../static/music/song9.mp3",
        "cover":"../static/image/TrackCover/song9.jpg",
        "genre":"rock",
    },
    {
        "name":"Oh Santa!",
        "id":"song10",
        "album":"album5",
        "artist":"artist2",
        "url":"../static/music/song10.mp3",
        "cover":"../static/image/TrackCover/song10.jpg",
        "genre":"country",
    },
    {
        "name":"One Child",
        "id":"song11",
        "album":"album5",
        "artist":"artist2",
        "url":"../static/music/song11.mp3",
        "cover":"../static/image/TrackCover/song11.jpg",
        "genre":"country",
    },
    {
        "name":"When Christmas Comes",
        "id":"song12",
        "album":"album5",
        "artist":"artist2",
        "url":"../static/music/song12.mp3",
        "cover":"../static/image/TrackCover/song12.jpg",
        "genre":"country",
    },
    {
        "name":"Fantasy",
        "id":"song13",
        "album":"album6",
        "artist":"artist2",
        "url":"../static/music/song13.mp3",
        "cover":"../static/image/TrackCover/song13.jpg",
        "genre":"country",
    },
    {
        "name":"Always Be My Baby",
        "id":"song14",
        "album":"album6",
        "artist":"artist2",
        "url":"../static/music/song14.mp3",
        "cover":"../static/image/TrackCover/song14.jpg",
        "genre":"country",
    },
    {
        "name":"bellyache",
        "id":"song15",
        "album":"album7",
        "artist":"artist3",
        "url":"../static/music/song15.mp3",
        "cover":"../static/image/TrackCover/song15.jpg",
        "genre":"rap",
    },
    {
        "name":"my boy",
        "id":"song16",
        "album":"album7",
        "artist":"artist3",
        "url":"../static/music/song16.mp3",
        "cover":"../static/image/TrackCover/song16.jpg",
        "genre":"rap",
    },
    {
        "name":"bad guy",
        "id":"song17",
        "album":"album8",
        "artist":"artist3",
        "url":"../static/music/song17.mp3",
        "cover":"../static/image/TrackCover/song17.jpg",
        "genre":"rap",
    },
    {
        "name":"xanny",
        "id":"song18",
        "album":"album8",
        "artist":"artist3",
        "url":"../static/music/song18.mp3",
        "cover":"../static/image/TrackCover/song18.jpg",
        "genre":"rap",
    },
    {
        "name":"Circles",
        "id":"song19",
        "album":"album9",
        "artist":"artist4",
        "url":"../static/music/song19.mp3",
        "cover":"../static/image/TrackCover/song19.jpg",
        "genre":"rap",
    },
    {
        "name":"Sunflower",
        "id":"song20",
        "album":"album9",
        "artist":"artist4",
        "url":"../static/music/song20.mp3",
        "cover":"../static/image/TrackCover/song20.jpg",
        "genre":"rap",
    },
    {
        "name":"What Lovers Do",
        "id":"song21",
        "album":"album10",
        "artist":"artist5",
        "url":"../static/music/song21.mp3",
        "cover":"../static/image/TrackCover/song21.jpg",
        "genre":"rap",
    },
    {
        "name":"Girls Like You",
        "id":"song22",
        "album":"album10",
        "artist":"artist5",
        "url":"../static/music/song22.mp3",
        "cover":"../static/image/TrackCover/song22.jpg",
        "genre":"rap",
    },
    {
        "name":"Kill Em with Kindness",
        "id":"song23",
        "album":"album11",
        "artist":"artist6",
        "url":"../static/music/song23.mp3",
        "cover":"../static/image/TrackCover/song23.jpg",
        "genre":"pop",
    },
    {
        "name":"Same Old Love",
        "id":"song24",
        "album":"album11",
        "artist":"artist6",
        "url":"../static/music/song24.mp3",
        "cover":"../static/image/TrackCover/song24.jpg",
        "genre":"pop",
    },
    {
        "name":"Senorita",
        "id":"song25",
        "album":"album12",
        "artist":"artist7",
        "url":"../static/music/song25.mp3",
        "cover":"../static/image/TrackCover/song25.jpg",
        "genre":"pop",
    },
    {
        "name":"My Oh My",
        "id":"song26",
        "album":"album12",
        "artist":"artist7",
        "url":"../static/music/song26.mp3",
        "cover":"../static/image/TrackCover/song26.jpg",
        "genre":"pop",
    },
    
]








